### ISSUE TITLE
MTC/MTL 全新重构！

### ISSUE THREAD

**Issue by Buelie** [Buelie/MinecraftTechLauncher#2]
**我们发现，启动器的很多代码是不必要的，为了优化性能，我们决定重构MTC/MTL以及相关的API，当然，我们打算同步更新新的GUI界面，使用户更容易上手**

> **需要重构的部分:**
* **JSON/XML/PY API**
* **旧的GUI**
* **所有类/函数**
* **配置文件**

> **开发规划:**
* **配置文件变更为JSON（彻底废除XML/YAML）**
* **将可以多线程运行的栈全部改为多线程（async）**
* **[【试验】](#)加入JS/TS/JAVA插件支持**
* **将重构的功能发布于 2023.7.16发布的 正式版-0.0.3 与大家相见**

# 这些功能将于2023.7.5发布的 Beta-0.0.6 版本与大家相见！！！

**欢迎您来提出建议！**

**Comment by Zaitonn** [comment]
https://github.com/Buelie/MinecraftTechLauncher/blob/1a09d27d6c2de1dd3975697ee495bc998f0e6e11/main.py#L10-L22

判断Boolean有点多余，，

**Comment by Buelie** [comment]
软件按照MCBBS的标准进行开发
Bool是用于判断是否生成文件

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年6月23日 20:04
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Buelie/MinecraftTechLauncher] MTC/MTL 全新重构！ (Issue #2)


https://github.com/Buelie/MinecraftTechLauncher/blob/1a09d27d6c2de1dd3975697ee495bc998f0e6e11/main.py#L10-L22

判断Boolean有点多余，，

―

**Comment by Zaitonn** [comment]
>软件按照MCBBS的标准进行开发

这是啥
![IC(Q~)T3GU~ET$VOWV BBAS](https://github.com/Buelie/MinecraftTechLauncher/assets/103164490/b0cc5bf2-c418-4ecd-bd91-2fb47b3b0850)

**Comment by Buelie** [comment]
MCBBS标准：
启动器只能是单个EXE文件
EXE文件不得过大(>2.5G)

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年6月23日 20:04
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Buelie/MinecraftTechLauncher] MTC/MTL 全新重构！ (Issue #2)


https://github.com/Buelie/MinecraftTechLauncher/blob/1a09d27d6c2de1dd3975697ee495bc998f0e6e11/main.py#L10-L22

判断Boolean有点多余，，

―

**Comment by Buelie** [comment]
可以从：https://www.minebbs.com/resources/minecraft-mtc.5951/version/19459/download 下载软件，
点击运行后，可以发现所在目录会多出两个文件夹
Bool语句就是用于判断是否插件文件夹

**Comment by Zaitonn** [comment]
我的意思是

1. 你不需要` if os.path.isdir('.minecraft/versions') == False:`这样写
    - `os.path.isdir`返回的就是boolean，加个`not`就行了，if可以直接判断，不需要` == False`
2. 直接`os.makedirs('path...', exist_ok=true)`即可
    - 不需要判断是否存在指定的目录

**Comment by Buelie** [comment]
会覆盖已有内容
